name: UP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: downlaod
      run: |
          apt install wget -y
          wget https://github.com/ProtonVPN/win-app/releases/download/3.2.9/ProtonVPN_v3.2.9.exe
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
          name: ProtonVPN_v3.2.9.exe
          path: ProtonVPN_v3.2.9.exe
