name: UP&&download

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: downlaod
      run: |
       wget https://builds.paranoidandroid.co/aospa-uvite-beta-mi439-20231231.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: aospa-uvite-beta-mi439-20231231
          path: aospa-uvite-beta-mi439-20231231.zip
